# Generated by Django 3.1.3 on 2020-12-06 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201206_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time_stamp',
            field=models.DateTimeField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
